### ISSUE TITLE
[Important] Remove large header banner from home page

### ISSUE THREAD

**Issue by pickerflicker** [stevenbarragan/swiftnote#11]
Remove large banner from index page.

It takes up the entire screen on laptops:

<img width="1454" alt="banners_and_alerts_and_pokemon_go_pro_tips" src="https://cloud.githubusercontent.com/assets/5424130/17046822/60cb333c-4f8c-11e6-9ccd-02368fb3406b.png">

**Comment by stevenbarragan** [comment]
donde
