### ISSUE TITLE
[Important] Fix Navigation Bar

### ISSUE THREAD

**Issue by pickerflicker** [stevenbarragan/swiftnote#13]
1) Can we rename copy to the following (the character counts are all similar):

"Definitive Starter's Guide"
"Power Leveling Guide"
"GPS Spoofing Guide"

2)  Add a hover effect to nav items to better illustrate they're clickable?

<img width="1434" alt="banners_and_alerts_and_pokemon_go_pro_tips" src="https://cloud.githubusercontent.com/assets/5424130/17046871/f3019002-4f8c-11e6-8041-86e6aae99a32.png">

**Comment by stevenbarragan** [comment]
Done!
