### ISSUE TITLE
Remove Header Banner Ad

### ISSUE THREAD

**Issue by pickerflicker** [stevenbarragan/swiftnote#15]
I think having an ad directly in our header makes the site feel too spammy. Let's focus on providing smooth user experience and build up readership before trying to milk them  =)

<img width="1228" alt="when_to_power_up_or_evolve_your_pokemon" src="https://cloud.githubusercontent.com/assets/5424130/17046943/ad791bda-4f8d-11e6-99e0-30a5519d5bed.png">

**Comment by stevenbarragan** [comment]
done
